Repository sparta-tenten/tenten-backend, pull requests merged in 2025-02, with the labels that each got.

#3 chore: db connection
  .gitignore
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore

#9 Feat: 회원,지역 엔티티 구현
  src/main/java/com/sparta/tentenbackend/domain/region/entity/Region.java
  src/main/java/com/sparta/tentenbackend/domain/region/repository/RegionRepository.java
  src/main/java/com/sparta/tentenbackend/domain/region/service/RegionService.java
  src/main/java/com/sparta/tentenbackend/domain/user/controller/UserController.java
  src/main/java/com/sparta/tentenbackend/domain/user/entity/User.java
  src/main/java/com/sparta/tentenbackend/domain/user/entity/UserRoleEnum.java
  src/main/java/com/sparta/tentenbackend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/tentenbackend/domain/user/service/UserService.java
Labels: feature

#12 Feat: swagger configuration
  build.gradle
  src/main/java/com/sparta/tentenbackend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/tentenbackend/global/config/SwaggerConfig.java
Labels: chore, feature

#20 Feat: 법정동 코드 기반 엔티티 구현 및 시드 데이터 Insert
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/entity/DeliveryAddress.java
  src/main/java/com/sparta/tentenbackend/domain/region/entity/City.java
  src/main/java/com/sparta/tentenbackend/domain/region/entity/District.java
  src/main/java/com/sparta/tentenbackend/domain/region/entity/Town.java
  src/main/java/com/sparta/tentenbackend/domain/user/entity/User.java
  src/main/resources/town_code_insert/generate_insert.py
  src/main/resources/town_code_insert/insert_queries.sql
  src/main/resources/town_code_insert/town_code.txt
Labels: feature

#23 Feat: 배송지 관련 API 구현
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/controller/DeliveryAddressController.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/dto/CreateDeliveryAddressRequest.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/dto/DeliveryAddressResponse.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/dto/UpdateDeliveryAddressRequest.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/entity/DeliveryAddress.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/repository/DeliveryAddressRepository.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/service/DeliveryAddressService.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/service/DeliveryAddressServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/order/entity/Order.java
  src/main/java/com/sparta/tentenbackend/domain/region/entity/District.java
  src/main/java/com/sparta/tentenbackend/domain/region/entity/Town.java
  src/main/java/com/sparta/tentenbackend/domain/region/repository/TownRepository.java
  src/main/java/com/sparta/tentenbackend/domain/region/service/TownService.java
  src/main/java/com/sparta/tentenbackend/domain/region/service/TownServiceImpl.java
  src/main/java/com/sparta/tentenbackend/global/BaseEntity.java
  src/main/java/com/sparta/tentenbackend/global/exception/GlobalExceptionAdvice.java
Labels: feature

#28 feat: Add Store API 구현
  build.gradle
  src/main/java/com/sparta/tentenbackend/TentenBackendApplication.java
  src/main/java/com/sparta/tentenbackend/domain/menu/entity/Menu.java
  src/main/java/com/sparta/tentenbackend/domain/menu/entity/MenuOption.java
  src/main/java/com/sparta/tentenbackend/domain/menu/entity/MenuOrder.java
  src/main/java/com/sparta/tentenbackend/domain/menu/entity/MenuOrderOption.java
  src/main/java/com/sparta/tentenbackend/domain/menu/repository/MenuOptionRepository.java
  src/main/java/com/sparta/tentenbackend/domain/menu/repository/MenuOrderOptionRepository.java
  src/main/java/com/sparta/tentenbackend/domain/menu/repository/MenuOrderRepository.java
  src/main/java/com/sparta/tentenbackend/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/tentenbackend/domain/store/controller/StoreController.java
  src/main/java/com/sparta/tentenbackend/domain/store/dto/StoreRequestDto.java
  src/main/java/com/sparta/tentenbackend/domain/store/dto/StoreResponseDto.java
  src/main/java/com/sparta/tentenbackend/domain/store/entity/Store.java
  src/main/java/com/sparta/tentenbackend/domain/store/repository/StoreRepository.java
  src/main/java/com/sparta/tentenbackend/domain/store/service/StoreService.java
  src/main/java/com/sparta/tentenbackend/global/security/UserDetailsImpl.java
Labels: feature

#37 Feat: AI API 추가
  src/main/java/com/sparta/tentenbackend/domain/ai/controller/AiController.java
  src/main/java/com/sparta/tentenbackend/domain/ai/entity/Ai.java
  src/main/java/com/sparta/tentenbackend/domain/ai/service/AiService.java
  src/main/java/com/sparta/tentenbackend/domain/ai/service/AiServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/ai/service/GeminiService.java
  src/main/java/com/sparta/tentenbackend/global/config/RestTemplateConfig.java
  src/main/resources/application.yml
Labels: feature

#40 Feat: 카테고리/리뷰에 User, 가게에 평점 추가
  src/main/java/com/sparta/tentenbackend/domain/category/controller/CategoryController.java
  src/main/java/com/sparta/tentenbackend/domain/category/entity/Category.java
  src/main/java/com/sparta/tentenbackend/domain/category/service/CategoryService.java
  src/main/java/com/sparta/tentenbackend/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/controller/OwnerReviewController.java
  src/main/java/com/sparta/tentenbackend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/tentenbackend/domain/review/dto/CreateReviewRequestDto.java
  src/main/java/com/sparta/tentenbackend/domain/review/entity/Review.java
  src/main/java/com/sparta/tentenbackend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/OwnerReviewService.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/OwnerReviewServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/ReviewService.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/store/entity/Store.java
Labels: feature

#52 Feat: 유저별 권한부여 및 삭제 API 구현
  src/main/java/com/sparta/tentenbackend/domain/user/controller/UserController.java
  src/main/java/com/sparta/tentenbackend/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/tentenbackend/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/com/sparta/tentenbackend/domain/user/entity/User.java
  src/main/java/com/sparta/tentenbackend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/tentenbackend/domain/user/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/user/service/UserService.java
  src/main/java/com/sparta/tentenbackend/global/config/WebSecurityConfig.java
Labels: feature

#54 Feat: 리뷰 검색 및 정렬, 카테고리별 가게 목록 조회
  src/main/java/com/sparta/tentenbackend/TentenBackendApplication.java
  src/main/java/com/sparta/tentenbackend/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/menu/service/MenuService.java
  src/main/java/com/sparta/tentenbackend/domain/review/controller/OwnerReviewController.java
  src/main/java/com/sparta/tentenbackend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/tentenbackend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/tentenbackend/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/tentenbackend/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/OwnerReviewService.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/OwnerReviewServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/ReviewService.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/store/controller/StoreController.java
  src/main/java/com/sparta/tentenbackend/domain/store/repository/StoreRepository.java
  src/main/java/com/sparta/tentenbackend/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/tentenbackend/domain/store/repository/StoreRepositoryImpl.java
  src/main/java/com/sparta/tentenbackend/domain/store/service/StoreService.java
  src/main/resources/application.yml
Labels: feature

#60 Feat: Base Entity createdBy,updatedBy,deletedBy 추가 및 주문 파트 유저 추가 및 가게 주인 검증 AOP
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/controller/DeliveryAddressController.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/entity/DeliveryAddress.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/repository/DeliveryAddressRepository.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/service/DeliveryAddressService.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/service/DeliveryAddressServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/order/annotation/CheckOrderOwner.java
  src/main/java/com/sparta/tentenbackend/domain/order/aop/OwnerAuthorizationAspect.java
  src/main/java/com/sparta/tentenbackend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/tentenbackend/domain/order/controller/OwnerOrderController.java
  src/main/java/com/sparta/tentenbackend/domain/order/entity/Order.java
  src/main/java/com/sparta/tentenbackend/domain/order/entity/OrderStatus.java
  src/main/java/com/sparta/tentenbackend/domain/order/repository/OrderRepositoryQuery.java
  src/main/java/com/sparta/tentenbackend/domain/order/repository/OrderRepositoryQueryImpl.java
  src/main/java/com/sparta/tentenbackend/domain/order/service/OrderRepositoryService.java
  src/main/java/com/sparta/tentenbackend/domain/order/service/OrderRepositoryServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/order/service/OrderService.java
  src/main/java/com/sparta/tentenbackend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/tentenbackend/domain/user/service/UserService.java
  src/main/java/com/sparta/tentenbackend/global/AuditorAwareImpl.java
  src/main/java/com/sparta/tentenbackend/global/BaseEntity.java
  src/main/java/com/sparta/tentenbackend/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/tentenbackend/global/exception/BadRequestException.java
  src/main/resources/town_code_insert/insert_test_data_queires.sql
Labels: feature

#63 feat: 배달지 주소, 주문 페이징 처리 디벨롭
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/controller/DeliveryAddressController.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/repository/DeliveryAddressRepositoryQuery.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/repository/DeliveryAddressRepositoryQueryImpl.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/service/DeliveryAddressService.java
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/service/DeliveryAddressServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/tentenbackend/domain/order/controller/OwnerOrderController.java
  src/main/java/com/sparta/tentenbackend/domain/order/dto/OrderSearchRequest.java
  src/main/java/com/sparta/tentenbackend/domain/order/repository/OrderRepositoryQueryImpl.java
  src/main/java/com/sparta/tentenbackend/global/util/PageUtils.java
Labels: feature

#64 Feat: API 주소 권한 설정 및 리뷰/답글 삭제 후 재작성 등 코드 수정
  src/main/java/com/sparta/tentenbackend/domain/category/entity/Category.java
  src/main/java/com/sparta/tentenbackend/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/tentenbackend/domain/review/entity/OwnerReview.java
  src/main/java/com/sparta/tentenbackend/domain/review/entity/Review.java
  src/main/java/com/sparta/tentenbackend/domain/review/repository/OwnerReviewRepository.java
  src/main/java/com/sparta/tentenbackend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/OwnerReviewServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/tentenbackend/global/config/WebSecurityConfig.java
  src/main/resources/town_code_insert/insert_test_data_queires.sql
Labels: feature

#67 Release test
  Dockerfile
Labels: release

#68 Release
  .github/workflows/ci_cd.yml
Labels: release

#69 Release
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/dto/UpdateDeliveryAddressRequest.java
  src/main/java/com/sparta/tentenbackend/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/tentenbackend/domain/menu/dto/MenuResponse.java
  src/main/java/com/sparta/tentenbackend/domain/menu/dto/OptionResponse.java
  src/main/java/com/sparta/tentenbackend/domain/menu/entity/Menu.java
  src/main/java/com/sparta/tentenbackend/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/tentenbackend/domain/order/dto/OrderMenuResponse.java
  src/main/java/com/sparta/tentenbackend/domain/order/dto/OrderOptionResponse.java
  src/main/java/com/sparta/tentenbackend/domain/order/dto/OrderRequest.java
  src/main/java/com/sparta/tentenbackend/domain/order/dto/TemporaryOrderResponse.java
  src/main/java/com/sparta/tentenbackend/domain/order/entity/Order.java
  src/main/java/com/sparta/tentenbackend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/tentenbackend/domain/store/dto/StoreRequestDto.java
  src/main/java/com/sparta/tentenbackend/domain/store/entity/Store.java
  src/main/java/com/sparta/tentenbackend/domain/store/service/StoreService.java
  src/main/java/com/sparta/tentenbackend/domain/user/entity/User.java
Labels: release

#73 Rlease
  README.md
  src/main/java/com/sparta/tentenbackend/domain/delivery_address/repository/DeliveryAddressRepositoryQueryImpl.java
  src/main/java/com/sparta/tentenbackend/domain/user/controller/UserController.java
Labels: release
